teams <- read.csv("teams2016.csv", header = TRUE)
dimnames(teams)[[1]] <- teams$X
teams$X <- NULL
library(shinydashboard)
sidebar <- dashboardSidebar(width = 250, sidebarMenu(
                            menuItem("Win Probability - Matchups", tabName = 'wpSpecific', icon = icon('fa fa-angle-right')),
                            menuItem("Run Expectancy", tabName = "re", icon = icon("fa fa-angle-right")),
                            menuItem("Hit Probabilities - Comparison", tabName = "probs", icon = icon("fa fa-angle-right"))))
body <- dashboardBody(  
          tabItems(
              tabItem(tabName = "re", style="height:1000px", fluidRow(
                      column(width = 8, fluidRow(style="padding-left:25px",
                         selectizeInput("home","Home Team:", choices = sort(dimnames(teams)[[1]]),options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                         selectizeInput("batter","Batting Team:", choices = sort(dimnames(teams)[[1]]), options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                         tags$head(
                           tags$style(HTML(".selectize-input.input-active, .selectize-input.input-active:hover, .selectize-control.multi .selectize-input.focus {border-color: navy !important;}.selectize-dropdown .active {background: #ADC4EC !important;}"))),
                         selectizeInput("pitcher","Pitcher's Team:", choices = sort(dimnames(teams)[[1]]), options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                         actionButton("info", "Submit Game Info",style="color: #lightgrey;background-color: #306EFF; border-color: #2e6da4;"),
                         br(),
                         br(),
                         uiOutput("namePitcher"),
                         br(),
                         uiOutput("nameBatter"),
                         br(),
                         radioButtons('s_outs2','Outs',c('0','1','2'),inline=TRUE),
                         br(),
                         radioButtons('s_first2','Baserunner on First?',c('No','Yes'),inline=TRUE),
                         br(),
                         radioButtons('s_second2','Baserunner on Second?',c('No','Yes'),inline=TRUE),
                         br(),
                         radioButtons('s_third2','Baserunner on Third?',c('No','Yes'),inline=TRUE),
                         br(),
                         radioButtons('balls2','Balls?',c('0','1','2','3'),inline=TRUE),
                         br(),
                         radioButtons('strikes2','Strikes?',c('0','1','2'),inline=TRUE),
                         actionButton("state_button2", "Get Run Expectancy",style="color: #lightgrey; background-color: #306EFF; border-color: #2e6da4"))),
                      infoBoxOutput("runs"))),
            tabItem(tabName = 'wpSpecific',style="height:1290px",
                      column(width = 8, fluidRow(style="padding-left:25px",
                          selectizeInput("home_team","Home Team:", choices = sort(dimnames(teams)[[1]]), options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                          tags$head(tags$style(HTML(".selectize-input.input-active, .selectize-input.input-active:hover, .selectize-control.multi .selectize-input.focus {border-color: navy !important;}.selectize-dropdown .active {background: #ADC4EC !important;}"))),
                          selectizeInput("visiting_team", "Visiting Team", choices = sort(dimnames(teams)[[1]]), options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                          textInput('inning','Inning:',value=1),
                          radioButtons('half_inning','Inning:',c('Top','Bottom'),inline=TRUE),
                          br(),
                          actionButton("info_button", "Submit Game Info",style="color: #lightgrey; background-color: #306EFF; border-color: #2e6da4;"),
                          br(),
                          br(),
                          br(),
                          textInput('vis_score','Visitors Score:',value=0),
                          br(),
                          textInput('home_score','Home Score:',value=0),
                          br(),
                          uiOutput("pitcher_name"),
                          br(),
                          uiOutput("batter_name"),
                          br(),
                          radioButtons('s_outs','Outs',c('0','1','2'),inline=TRUE),
                          br(),
                          radioButtons('s_first','Baserunner on First?',c('No','Yes'),inline=TRUE),
                          br(),
                          radioButtons('s_second','Baserunner on Second?',c('No','Yes'),inline=TRUE),
                          br(),
                          radioButtons('s_third','Baserunner on Third?',c('No','Yes'),inline=TRUE),
                          br(),
                          radioButtons('balls','Balls?',c('0','1','2','3'),inline=TRUE),
                          br(),
                          radioButtons('strikes','Strikes?',c('0','1','2'),inline=TRUE),
                          uiOutput("state_button"))),
                          infoBoxOutput("home"),
                          infoBoxOutput("away")),
            tabItem(tabName = "probs", style = "height:2300px;",
                    column(width = 6, fluidRow(style = "padding-left:25px;padding-bottom:50px",
                          uiOutput("player1"),
                          tags$head(tags$style("#player1{color: black;font-size: 15px;font-style: bold;text-align: center;}")),
                          selectizeInput("p.home","Home Team:", choices = sort(dimnames(teams)[[1]]), options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                            tags$head(tags$style(HTML(".selectize-input.input-active, .selectize-input.input-active:hover, .selectize-control.multi .selectize-input.focus {border-color: navy !important;}.selectize-dropdown .active {background: #ADC4EC !important;}"))),
                          selectizeInput("visiting", "Visiting Team", choices = sort(dimnames(teams)[[1]]), options = list(placeholder = 'Please select a team', onInitialize = I('function() { this.setValue(""); }'))),
                          radioButtons('half', 'Inning:', c('Top', 'Bottom'), inline = TRUE),
                          actionButton("midbutton", "Submit Game Info",style="color: #lightgrey; background-color: #306EFF; border-color: #2e6da4;"),
                          br(),
                          br(),
                          uiOutput("the_pitcher"),
                          uiOutput("the_batter"),
                          radioButtons('p_outs','Outs',c('0','1','2'),inline=TRUE),
                          br(),
                          radioButtons('p_first','Baserunner on First?',c('No','Yes'),inline=TRUE),
                          br(),
                          radioButtons('p_second','Baserunner on Second?',c('No','Yes'),inline=TRUE),
                          br(),
                          radioButtons('p_third','Baserunner on Third?',c('No','Yes'),inline=TRUE),
                          br(),
                          radioButtons('p_balls','Balls?',c('0','1','2','3'),inline=TRUE),
                          br(),
                          radioButtons('p_strikes','Strikes?',c('0','1','2'),inline=TRUE),
                          br(),
                          # uiOutput("one_player_comparison"),
                          # div(style="display:inline-block; float:right",actionButton("one_player_comparison", "Get Hit Probabilities", style="color: #lightgrey; background-color: #306EFF; border-color: #2e6da4; float:right")),
                          div(style="display:inline-block; float:left",actionButton('compare_button', "Make a Comparison", style="color: #lightgrey; background-color: #4AA02C; border-color: #2e6da4; float:right")),
                          br())),
                    uiOutput("player2"),
                    tags$head(tags$style("#player2{color: black;font-size: 15px;font-style: bold;text-align: center;}")),
                    uiOutput("compare"),
                    dataTableOutput('comparisontable'),
                    tags$head(tags$style('#comparisontable{.input-active:hover{background-color: yellow};')))))
              
dashboardPage(
  dashboardHeader(title = span(tagList(icon("fa fa-shield"), "numberFire RE & WP")), titleWidth = 250),
  sidebar,
  body,
  skin = 'black'
)
